add buy product
dark4dragon/JS_pnakonechnyi pull request #1
Opened 2022-08-31 18:49 UTC by dark4dragon

Added buy product functionality.
Added price compare in product page and cart.
Not added reference code validataion

2022-08-31 21:16 UTC, adudyak requested changes

2022-08-31 21:16 UTC, adudyak commented on pages/cart.js
> +    return pin = await I.grabTextFrom(this.totalPrice);
remove variable `pin`

2022-08-31 21:16 UTC, adudyak commented on pages/cart.js
> +    return pin = await I.grabTextFromAll(this.orderComplete);
remove `pin`

2022-08-31 21:16 UTC, adudyak commented on pages/product.js
> +    return pin = await I.grabTextFrom(this.productPrice);
remove `pin`

2022-08-31 21:16 UTC, adudyak commented on test/test_store.js
> +xScenario('registration', ({ I, homePage, authPage, createAccountPage, myAccountPage }) => {
keep scenario active without `x`

2022-08-31 21:16 UTC, adudyak commented on test/test_store.js
> +    I.openProductPage();
use `I.amOnPage()`, we will need to parametrize link later

2022-08-31 21:16 UTC, adudyak commented on test/test_store.js
> +    console.log(+productPrice.slice(1) + 3.30);
remove `console.log()`s

2022-08-31 21:16 UTC, adudyak commented on test/test_store.js
> +    I.assertEqual(+productPrice.slice(1) + 3.30, +totalPrice.slice(1));
do `slice()` and numeric conversion inside of `getPrice()` methods

2022-08-31 21:16 UTC, adudyak commented on test/test_store.js
> +    I.assertEqual(+productPrice.slice(1) + 3.30, +totalPrice.slice(1));
get shipping cost from page

2022-08-31 21:16 UTC, adudyak commented on test/test_store.js
> +    let referenceCode = await cartPage.getReferenceCode();
this method should return reference code, you should not do any conversions in scenario

2022-08-31 21:16 UTC, adudyak commented on test/test_store.js
> +    console.log(stringCode[216]);
you referenced to 216th symbol of string, but need to get a substring.
refer to [https://learn.javascript.ru/string#poluchenie-podstroki](https://learn.javascript.ru/string#poluchenie-podstroki)

2022-09-01 14:10 UTC, dark4dragon commented on pages/cart.js
> +    return pin = await I.grabTextFrom(this.totalPrice);
done

2022-09-01 14:10 UTC, dark4dragon commented on pages/cart.js
> +    return pin = await I.grabTextFromAll(this.orderComplete);
done

2022-09-01 14:10 UTC, dark4dragon commented on pages/product.js
> +    return pin = await I.grabTextFrom(this.productPrice);
done

2022-09-01 14:11 UTC, dark4dragon commented on test/test_store.js
> +xScenario('registration', ({ I, homePage, authPage, createAccountPage, myAccountPage }) => {
done

2022-09-01 14:11 UTC, dark4dragon commented on test/test_store.js
> +    I.openProductPage();
done

2022-09-01 14:11 UTC, dark4dragon commented on test/test_store.js
> +    I.assertEqual(+productPrice.slice(1) + 3.30, +totalPrice.slice(1));
done

2022-09-01 14:12 UTC, dark4dragon commented on test/test_store.js
> +    let referenceCode = await cartPage.getReferenceCode();
fixed

2022-09-01 14:12 UTC, dark4dragon commented on test/test_store.js
> +    console.log(stringCode[216]);
done

2022-09-01 14:26 UTC, adudyak commented on pages/cart.js
> +  proceedingCheckout() {
keep infinitive state `proceedToCheckout`, but here it is better to name `completePurchase`, because your method not just proceed to checkout, but completes the whole process

2022-09-01 14:26 UTC, adudyak commented on pages/product.js
> +    I.click(this.proceedToCheckoutButton);
`proceedToCheckout()` should be a separate method, because it is not related to `addToCart()`

2022-09-01 14:26 UTC, adudyak commented on test/test_store.js
> -
rename test file to `store_test.js` and update config

2022-09-01 14:26 UTC, adudyak commented on test/test_store.js
> +    I.assertEqual((productPrice + shippingPrice + taxPrice), totalPrice);
add 3rd parameter - message in case of no match.

2022-09-01 14:28 UTC, dark4dragon commented on pages/cart.js
> +  proceedingCheckout() {
done

2022-09-01 14:33 UTC, dark4dragon commented on pages/product.js
> +    I.click(this.proceedToCheckoutButton);
done

2022-09-01 14:37 UTC, dark4dragon commented on test/test_store.js
> -
done

2022-09-01 14:37 UTC, dark4dragon commented on test/test_store.js
> +    I.assertEqual((productPrice + shippingPrice + taxPrice), totalPrice);
done

2022-09-01 14:54 UTC, merged